name: smplayer
version: '18.2.0'
summary: Free Media Player with built-in codecs
description: |
  SMPlayer is a free media player for Windows and Linux with built-in codecs
  that can play virtually all video and audio formats. It doesn't need any
  external codecs. Just install SMPlayer and you'll be able to play all
  formats without the hassle to find and install codec packs.

grade: stable
architectures: [amd64]
confinement: strict

parts:
  desktop-qt4:
    source-tag: v20180201

  ppas:
    plugin: nil
    prepare: |
      add-apt-repository ppa:mc3man/mpv-tests -y
      add-apt-repository ppa:mc3man/ffmpeg-test -y
      add-apt-repository ppa:rvm/smplayer-qt4 -y
      apt update
      apt upgrade -yy
    build-packages:
      - software-properties-common

  smplayer:
    plugin: nil
    after:
      - ppas
      - desktop-qt4
    stage-packages:
      - libc6
      - libgcc1
      - libqt4-dbus
      - libqt4-network
      - libqt4-script
      - libqt4-xml
      - libqtcore4
      - libqtgui4
      - libstdc++6
      - zlib1g
      - smplayer
      - smtube
      - mpv

  fixicons:
    plugin: nil
    after:
      - smplayer
    install: |
      sed -i 's|Icon=smplayer|Icon=/usr/share/icons/hicolor/scalable/apps/smplayer\.svg|' $SNAPCRAFT_STAGE/usr/share/applications/smplayer.desktop
      sed -i 's|Icon=smtube|Icon=/usr/share/icons/hicolor/256x256/apps/smtube\.png|' $SNAPCRAFT_STAGE/usr/share/applications/smtube.desktop

apps:
  smplayer:
    command: bin/desktop-launch $SNAP/usr/bin/smplayer
    desktop: usr/share/applications/smplayer.desktop
    plugs: [ wayland, unity7, x11, opengl, home, desktop, desktop-legacy, pulseaudio, network-manager, network-control, screen-inhibit-control, mount-observe ]
    slots: [mpris]

  smtube:
    command: bin/desktop-launch $SNAP/usr/bin/smtube
    desktop: usr/share/applications/smtube.desktop
    plugs: [ wayland, unity7, x11, opengl, home, desktop, desktop-legacy, pulseaudio, network-manager, network-control ]
    slots: [mpris]